name = "worker"
main = "dist/index.mjs"
compatibility_date = "2023-05-05"

[build]
command = "node build.js"

[build.upload]
format = "modules"

[durable_objects]
bindings = [
  { name = "WOODCHIP", class_name = "Woodchip" },
]

